//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonerosWeb.Resourses {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonerosWeb.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar la Acta.
        /// </summary>
        public static string errorBuscarActa {
            get {
                return ResourceManager.GetString("errorBuscarActa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar el Coordinador o Enlace.
        /// </summary>
        public static string errorBuscarDesignacionInstitucion {
            get {
                return ResourceManager.GetString("errorBuscarDesignacionInstitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar el Personero.
        /// </summary>
        public static string errorBuscarDesignacionMesa {
            get {
                return ResourceManager.GetString("errorBuscarDesignacionMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar el Distrito.
        /// </summary>
        public static string errorBuscarDistrito {
            get {
                return ResourceManager.GetString("errorBuscarDistrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar la Institución.
        /// </summary>
        public static string errorBuscarInstitucion {
            get {
                return ResourceManager.GetString("errorBuscarInstitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar la Mesa.
        /// </summary>
        public static string errorBuscarMesa {
            get {
                return ResourceManager.GetString("errorBuscarMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar la Persona.
        /// </summary>
        public static string errorBuscarPersona {
            get {
                return ResourceManager.GetString("errorBuscarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar el Tipo de Elección.
        /// </summary>
        public static string errorBuscarTipoEleccion {
            get {
                return ResourceManager.GetString("errorBuscarTipoEleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar el Tipo de Usuario.
        /// </summary>
        public static string errorBuscarTipoUsuario {
            get {
                return ResourceManager.GetString("errorBuscarTipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar el Usuario.
        /// </summary>
        public static string errorBuscarUsuario {
            get {
                return ResourceManager.GetString("errorBuscarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear la Acta.
        /// </summary>
        public static string errorCrearActa {
            get {
                return ResourceManager.GetString("errorCrearActa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el Coordinador o Enlace.
        /// </summary>
        public static string errorCrearDesignacionInstitucion {
            get {
                return ResourceManager.GetString("errorCrearDesignacionInstitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el Personero.
        /// </summary>
        public static string errorCrearDesignacionMesa {
            get {
                return ResourceManager.GetString("errorCrearDesignacionMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el Distrito.
        /// </summary>
        public static string errorCrearDistrito {
            get {
                return ResourceManager.GetString("errorCrearDistrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear la Institución.
        /// </summary>
        public static string errorCrearInstitucion {
            get {
                return ResourceManager.GetString("errorCrearInstitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear la Mesa.
        /// </summary>
        public static string errorCrearMesa {
            get {
                return ResourceManager.GetString("errorCrearMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear la Persona.
        /// </summary>
        public static string errorCrearPersona {
            get {
                return ResourceManager.GetString("errorCrearPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el Tipo de Elección.
        /// </summary>
        public static string errorCrearTipoEleccion {
            get {
                return ResourceManager.GetString("errorCrearTipoEleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el Tipo de Usuario.
        /// </summary>
        public static string errorCrearTipoUsuario {
            get {
                return ResourceManager.GetString("errorCrearTipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el Usuario.
        /// </summary>
        public static string errorCrearUsuario {
            get {
                return ResourceManager.GetString("errorCrearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar la Acta.
        /// </summary>
        public static string errorEliminarActa {
            get {
                return ResourceManager.GetString("errorEliminarActa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el Coordinador o Enlace.
        /// </summary>
        public static string errorEliminarDesignacionInstitucion {
            get {
                return ResourceManager.GetString("errorEliminarDesignacionInstitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el Personero.
        /// </summary>
        public static string errorEliminarDesignacionMesa {
            get {
                return ResourceManager.GetString("errorEliminarDesignacionMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el Distrito.
        /// </summary>
        public static string errorEliminarDistrito {
            get {
                return ResourceManager.GetString("errorEliminarDistrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar la Institución.
        /// </summary>
        public static string errorEliminarInstitucion {
            get {
                return ResourceManager.GetString("errorEliminarInstitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar la Mesa.
        /// </summary>
        public static string errorEliminarMesa {
            get {
                return ResourceManager.GetString("errorEliminarMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar la Persona.
        /// </summary>
        public static string errorEliminarPersona {
            get {
                return ResourceManager.GetString("errorEliminarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el Tipo de Elección.
        /// </summary>
        public static string errorEliminarTipoEleccion {
            get {
                return ResourceManager.GetString("errorEliminarTipoEleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el Tipo de Usuario.
        /// </summary>
        public static string errorEliminarTipoUsuario {
            get {
                return ResourceManager.GetString("errorEliminarTipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el Usuario.
        /// </summary>
        public static string errorEliminarUsuario {
            get {
                return ResourceManager.GetString("errorEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar Iniciar Sesión.
        /// </summary>
        public static string errorLoginUsuario {
            get {
                return ResourceManager.GetString("errorLoginUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al modificar la Acta.
        /// </summary>
        public static string errorModificarActa {
            get {
                return ResourceManager.GetString("errorModificarActa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al modificar el Coordinador o Enlace.
        /// </summary>
        public static string errorModificarDesignacionInstitucion {
            get {
                return ResourceManager.GetString("errorModificarDesignacionInstitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al modificar el Personero.
        /// </summary>
        public static string errorModificarDesignacionMesa {
            get {
                return ResourceManager.GetString("errorModificarDesignacionMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al modificar el Distrito.
        /// </summary>
        public static string errorModificarDistrito {
            get {
                return ResourceManager.GetString("errorModificarDistrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al modificar la Institución.
        /// </summary>
        public static string errorModificarInstitucion {
            get {
                return ResourceManager.GetString("errorModificarInstitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al modificar la Mesa.
        /// </summary>
        public static string errorModificarMesa {
            get {
                return ResourceManager.GetString("errorModificarMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al modificar la Persona.
        /// </summary>
        public static string errorModificarPersona {
            get {
                return ResourceManager.GetString("errorModificarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al modificar el Tipo de Elección.
        /// </summary>
        public static string errorModificarTipoEleccion {
            get {
                return ResourceManager.GetString("errorModificarTipoEleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al modificar el Tipo de Usuario.
        /// </summary>
        public static string errorModificarTipoUsuario {
            get {
                return ResourceManager.GetString("errorModificarTipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al modificar el Usuario.
        /// </summary>
        public static string errorModificarUsuario {
            get {
                return ResourceManager.GetString("errorModificarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener las Actas.
        /// </summary>
        public static string errorObtenerActas {
            get {
                return ResourceManager.GetString("errorObtenerActas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener los Coordinadores y Enlaces.
        /// </summary>
        public static string errorObtenerDesignacionesInstituciones {
            get {
                return ResourceManager.GetString("errorObtenerDesignacionesInstituciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener los Personeros.
        /// </summary>
        public static string errorObtenerDesignacionesMesas {
            get {
                return ResourceManager.GetString("errorObtenerDesignacionesMesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener los Distritos.
        /// </summary>
        public static string errorObtenerDistritos {
            get {
                return ResourceManager.GetString("errorObtenerDistritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener las Insituciones.
        /// </summary>
        public static string errorObtenerInstituciones {
            get {
                return ResourceManager.GetString("errorObtenerInstituciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener las Mesas.
        /// </summary>
        public static string errorObtenerMesas {
            get {
                return ResourceManager.GetString("errorObtenerMesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener las Personas.
        /// </summary>
        public static string errorObtenerPersonas {
            get {
                return ResourceManager.GetString("errorObtenerPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener los Tipos de Elecciones.
        /// </summary>
        public static string errorObtenerTiposElecciones {
            get {
                return ResourceManager.GetString("errorObtenerTiposElecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener los Tipos de Usuario.
        /// </summary>
        public static string errorObtenerTiposUsuario {
            get {
                return ResourceManager.GetString("errorObtenerTiposUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener los Usuarios.
        /// </summary>
        public static string errorObtenerUsuarios {
            get {
                return ResourceManager.GetString("errorObtenerUsuarios", resourceCulture);
            }
        }
    }
}
