//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonerosWeb.Resourses {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Icono {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icono() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonerosWeb.Resources.Icono", typeof(Icono).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bx bx-file-blank.
        /// </summary>
        public static string acta {
            get {
                return ResourceManager.GetString("acta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bx bx-building-house.
        /// </summary>
        public static string distrito {
            get {
                return ResourceManager.GetString("distrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bx bxs-institution.
        /// </summary>
        public static string institucion {
            get {
                return ResourceManager.GetString("institucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bx bx-chalkboard.
        /// </summary>
        public static string mesa {
            get {
                return ResourceManager.GetString("mesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bx bx-user.
        /// </summary>
        public static string persona {
            get {
                return ResourceManager.GetString("persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bx bx-select-multiple.
        /// </summary>
        public static string tipoEleccion {
            get {
                return ResourceManager.GetString("tipoEleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bx bxs-user-account.
        /// </summary>
        public static string tipoUsuario {
            get {
                return ResourceManager.GetString("tipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bx bx-user-circle.
        /// </summary>
        public static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
    }
}
